language: ruby
cache:
- bundler
install:
- gem install bundler -v 1.12
- bundle install
rvm:
- 2.2
- 2.3.0
- 2.4
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-chef.gemspec
- gem install sensu-plugins-chef-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: g/pQkLYUIQACeun9Cs+TaWvhO6VepD7nyQLpYhuBYXHNGIXJsgjgulr/SzYcrP+R4NZAzqse8bQTjHv+mGTa91nAxOHwMo7R8gmF/WsiuiPL1GpFR3EOYCgx8+IPQ8T0EnTRE5Nkf+25O5tPtbgPcUA/6jJHEEIxXtYfJd8l10s=
  gem: sensu-plugins-chef
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: sensu-plugins/sensu-plugins-chef
